version: "3.8"
services:
  api-service:
    build: ./API
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNET_VERSION=8.0.2
      - VITE_APP_API_BASE_URL=http://docker.host.internal:8080
