// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240318072248_gameWinCalculation")]
    partial class gameWinCalculation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("API.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResultLotteryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalWinning")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResultLotteryId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("API.Entities.Lottery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Lotteries");
                });

            modelBuilder.Entity("API.Entities.Game", b =>
                {
                    b.HasOne("API.Entities.Lottery", "ResultLottery")
                        .WithOne("Game")
                        .HasForeignKey("API.Entities.Game", "ResultLotteryId");

                    b.Navigation("ResultLottery");
                });

            modelBuilder.Entity("API.Entities.Lottery", b =>
                {
                    b.HasOne("API.Entities.Game", null)
                        .WithMany("LotteriesPlayed")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("API.Entities.Game", b =>
                {
                    b.Navigation("LotteriesPlayed");
                });

            modelBuilder.Entity("API.Entities.Lottery", b =>
                {
                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
